site_name: Snoozle
repo_url: https://github.com/charliejkendall/snoozle
repo_name: GitHub
edit_uri: docs/
site_description: Documentation for Snoozle
site_author: Charlie Kendall
copyright: Copyright (c) Charlie Kendall 2020