using Snoozle.Abstractions.Models;

namespace Snoozle.Abstractions
{
    /// <summary>
    /// Provides methods for setting the core property configuration values.
    /// </summary>
    public abstract class BasePropertyConfigurationBuilder<TResource, TProperty, TPropertyConfiguration>
        : IPropertyConfigurationBuilder<TProperty, TPropertyConfiguration>, IComputedValueBuilder<TProperty, TPropertyConfiguration>
        where TResource : class, IRestResource
        where TPropertyConfiguration : IPropertyConfiguration
    {
        /// <summary>
        /// Initialises a new instance of the <see cref="BasePropertyConfigurationBuilder{TResource, TProperty, TPropertyConfiguration}"/> class.
        /// </summary>
        /// <param name="propertyConfiguration">The property configuration that the builder configures.</param>
        protected BasePropertyConfigurationBuilder(TPropertyConfiguration propertyConfiguration)
        {
            PropertyConfiguration = propertyConfiguration;
        }

        /// <inheritdoc />
        public TPropertyConfiguration PropertyConfiguration { get; }

        /// <inheritdoc />
        public IPropertyConfigurationBuilder<TProperty, TPropertyConfiguration> IsReadOnly(bool isReadOnly = true)
        {
            PropertyConfiguration.IsReadOnly = isReadOnly;

            return this;
        }

        /// <inheritdoc />
        public IPropertyConfigurationBuilder<TProperty, TPropertyConfiguration> IsPrimaryIdentifier(bool isValueAutoGeneratedByDataStore = true)
        {
            PropertyConfiguration.IsPrimaryResourceIdentifier = true;
            IsReadOnly(isValueAutoGeneratedByDataStore);

            return this;
        }

        /// <inheritdoc />
        public IComputedValueBuilder<TProperty, TPropertyConfiguration> HasComputedValue(HttpVerbs endpointTriggers)
        {
            PropertyConfiguration.ValueComputationFunc = new ValueComputationFuncModel(endpointTriggers);

            return this;
        }
    }
}
